name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Cache Genezio binary
      - name: Cache Genezio binary
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/node/20.12.2/x64/bin/genezio
          key: ${{ runner.os }}-genezio-binary-${{ hashFiles('/opt/hostedtoolcache/node/20.12.2/x64/bin/genezio') }}
          restore-keys: |
            ${{ runner.os }}-genezio-binary-
      - uses: Genez-io/genezio-github-action@v1
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Check deps
        run: |
          node --version
          genezio --version
          which genezio
          which node
      - name: Deploy backend
        run: genezio deploy
