name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Genezio binary
        id: cache-genezio
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/node/20.12.2/x64/bin/genezio
          key: ${{ runner.os }}-genezio-binary
          restore-keys: |
            ${{ runner.os }}-genezio-binary
      - uses: Genez-io/genezio-github-action@v1
        if: steps.cache-genezio.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Debug Cache Restoration
        run: |
          ls -l /opt/hostedtoolcache/node/20.12.2/x64/bin/
          ls -l /opt/hostedtoolcache/node/20.12.2/x64/bin/genezio
      - name: Echo path
        run: echo $PATH
      - name: Check deps
        run: /opt/hostedtoolcache/node/20.12.2/x64/bin/genezio --version
      - name: Deploy backend
        run: /opt/hostedtoolcache/node/20.12.2/x64/bin/genezio deploy
